### ISSUE TITLE
thread 'main' panicked at 'index out of bounds

### ISSUE THREAD

**Issue by aadadurov** [progga/subtitles#1]
Hello! Tried to test the software on Linux Mint 21.1, but got an error:
**$ ~/projects/subtitles/target/release/subtitles --transcript ~/20230918.txt --length 415 > 20230918.srt**

thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/subtitle.rs:99:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

How can I fix it?

**Comment by progga** [comment]
Sorry for the trouble.  I am on the case.  I may have to ask you later for the transcript file if I can't troubleshoot it.  I will let you know in 24 hours.

**Comment by aadadurov** [comment]
> Sorry for the trouble. I am on the case. I may have to ask you later for the transcript file if I can't troubleshoot it. I will let you know in 24 hours.

Thanks for your reply! Your comment about the transcript file pointed me to the problem. I ran some tests and indeed there was a reference in the file that broke the program. It was a Bible verse containing a reference in this style (John 7:6). Removing it solves the problem

**Comment by progga** [comment]
Hmm.. it still shouldn't have crashed.  I inserted `(John 7:6)` in a sample text file but failed the reproduce the problem.  Unless you are working on a private video, would you mind sharing all or part of the transcript text so that I can troubleshoot better.

**Comment by aadadurov** [comment]
Below is what I'm doing when trying to generate srt. Real file is here [test_file](https://knebu.org/tmp/test.txt)

```
$ pwd
/home/user/tmp/subtitles/target/release
$ cat  ~/tmp/1.txt
Verse from the Bible (John. 7:6).
$ ./subtitles --transcript ~/tmp/1.txt --length 5  > ~/tmp/out.srt
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/subtitle.rs:99:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by progga** [comment]
Thanks a lot.  I can reproduce the problem.  This shouldn't happen.  I will see if I can come up with a fix.

**Comment by progga** [comment]
Hello, I have created a fix.  Would you mind trying it.  Here's one way to try this:
```
$ git clone --brance fix/1-non-alphabetic-sentence git@github.com:progga/subtitles.git
$ cd subtitles
$ cargo build --release
$ ./target/release/subtitles --transcript transcript-filename.txt --length 415
```

**Comment by aadadurov** [comment]
Hello! I pulled you fix and the error is gone now, thank you!

**Comment by progga** [comment]
Many thanks for testing the fix.  I have merged it and published a new version of the [crate](https://crates.io/crates/subtitles).
